// Generates src/environments/environment.ts from `.env` (or the process environment),
// since the Angular CLI doesn't read `.env` files itself. Runs before start/build/test.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const REQUIRED = {
  forecastUrl: 'FORECAST_URL',
  airQualityUrl: 'AIR_QUALITY_URL',
  searchUrl: 'SEARCH_URL',
  reverseGeocodeUrl: 'REVERSE_GEOCODE_URL',
};

/** Parses `KEY=value` lines, skipping blanks and `#` comments. */
function parseEnv(text) {
  const vars = {};
  for (const line of text.split(/\r?\n/)) {
    const match = line.match(/^\s*([\w.]+)\s*=\s*(.*?)\s*$/);
    if (match && !line.trim().startsWith('#')) {
      vars[match[1]] = match[2].replace(/^(['"])(.*)\1$/, '$2');
    }
  }
  return vars;
}

const fileVars = existsSync('.env') ? parseEnv(readFileSync('.env', 'utf8')) : {};
// Real environment variables win, so CI can override `.env`.
const vars = { ...fileVars, ...process.env };

const missing = Object.values(REQUIRED).filter((key) => !vars[key]);
if (missing.length) {
  console.error(`Missing ${missing.join(', ')}. Copy .env.example to .env and fill it in.`);
  process.exit(1);
}

const entries = Object.entries(REQUIRED)
  .map(([prop, key]) => `  ${prop}: ${JSON.stringify(vars[key])},`)
  .join('\n');

mkdirSync('src/environments', { recursive: true });
writeFileSync(
  'src/environments/environment.ts',
  `// Generated by scripts/set-env.mjs from .env — do not edit or commit.\nexport const environment = {\n${entries}\n};\n`,
);
